### ISSUE TITLE
Enable distribution to multiple workspaces

### ISSUE THREAD

**Issue by cakekindel** [cakekindel/egg-party#94]
As a Slack Admin, it would be convenient for me to be able to click a button to install Egg Party to my slack instance, rather than have to create a production instance of my own.

https://api.slack.com/start/distributing/public

###### *Screenshot of Slack App Distribution view*
![image](https://user-images.githubusercontent.com/12725400/71551294-40b07100-29a1-11ea-9efc-690619a2a4cf.png)

**Comment by cakekindel** [comment]
**Tasks:**
- [ ] feat(api): Add OAuth redirect URLs
- [ ] feat(db): Add storage for Slack Workspace info (tokens!)
- [ ] feat(api): Support message-sending for multiple workspaces
- [ ] smoke test multiple workspace installation, write more tasks if necessary
